# These are supported funding model platforms

# GitHub Sponsors (uncomment when you set up GitHub Sponsors)
# github: TenSoja

# Buy Me a Coffee integration
buy_me_a_coffee: tensoja

# Other platforms (available for future use)
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# liberapay: # Replace with a single Liberapay username

# Custom funding URLs (backup/additional options)
custom: ["https://www.buymeacoffee.com/tensoja"]
